# Erzeugt von tools/install_into_repo.py - nicht von Hand ändern.
set(FFMPEG_SOURCES_arm64-v8a
    ${FFMPEG_SRC}/compat/strtod.c
    ${FFMPEG_SRC}/libavcodec/aactab.c
    ${FFMPEG_SRC}/libavcodec/aarch64/fdctdsp_init_aarch64.c
    ${FFMPEG_SRC}/libavcodec/aarch64/fdctdsp_neon.S
    ${FFMPEG_SRC}/libavcodec/aarch64/h264chroma_init_aarch64.c
    ${FFMPEG_SRC}/libavcodec/aarch64/h264cmc_neon.S
    ${FFMPEG_SRC}/libavcodec/aarch64/h264qpel_init_aarch64.c
    ${FFMPEG_SRC}/libavcodec/aarch64/h264qpel_neon.S
    ${FFMPEG_SRC}/libavcodec/aarch64/hpeldsp_init_aarch64.c
    ${FFMPEG_SRC}/libavcodec/aarch64/hpeldsp_neon.S
    ${FFMPEG_SRC}/libavcodec/aarch64/idctdsp_init_aarch64.c
    ${FFMPEG_SRC}/libavcodec/aarch64/idctdsp_neon.S
    ${FFMPEG_SRC}/libavcodec/aarch64/me_cmp_init_aarch64.c
    ${FFMPEG_SRC}/libavcodec/aarch64/me_cmp_neon.S
    ${FFMPEG_SRC}/libavcodec/aarch64/simple_idct_neon.S
    ${FFMPEG_SRC}/libavcodec/aarch64/vc1dsp_init_aarch64.c
    ${FFMPEG_SRC}/libavcodec/aarch64/vc1dsp_neon.S
    ${FFMPEG_SRC}/libavcodec/aarch64/videodsp.S
    ${FFMPEG_SRC}/libavcodec/aarch64/videodsp_init.c
    ${FFMPEG_SRC}/libavcodec/ac3_parser.c
    ${FFMPEG_SRC}/libavcodec/acelp_filters.c
    ${FFMPEG_SRC}/libavcodec/acelp_vectors.c
    ${FFMPEG_SRC}/libavcodec/adts_parser.c
    ${FFMPEG_SRC}/libavcodec/allcodecs.c
    ${FFMPEG_SRC}/libavcodec/avcodec.c
    ${FFMPEG_SRC}/libavcodec/avdct.c
    ${FFMPEG_SRC}/libavcodec/bitstream.c
    ${FFMPEG_SRC}/libavcodec/bitstream_filters.c
    ${FFMPEG_SRC}/libavcodec/blockdsp.c
    ${FFMPEG_SRC}/libavcodec/bsf.c
    ${FFMPEG_SRC}/libavcodec/celp_filters.c
    ${FFMPEG_SRC}/libavcodec/codec_desc.c
    ${FFMPEG_SRC}/libavcodec/codec_par.c
    ${FFMPEG_SRC}/libavcodec/d3d11va.c
    ${FFMPEG_SRC}/libavcodec/decode.c
    ${FFMPEG_SRC}/libavcodec/dirac.c
    ${FFMPEG_SRC}/libavcodec/dv_profile.c
    ${FFMPEG_SRC}/libavcodec/encode.c
    ${FFMPEG_SRC}/libavcodec/error_resilience.c
    ${FFMPEG_SRC}/libavcodec/exif.c
    ${FFMPEG_SRC}/libavcodec/faandct.c
    ${FFMPEG_SRC}/libavcodec/faanidct.c
    ${FFMPEG_SRC}/libavcodec/fdctdsp.c
    ${FFMPEG_SRC}/libavcodec/get_buffer.c
    ${FFMPEG_SRC}/libavcodec/h263.c
    ${FFMPEG_SRC}/libavcodec/h263data.c
    ${FFMPEG_SRC}/libavcodec/h263dec.c
    ${FFMPEG_SRC}/libavcodec/h263dsp.c
    ${FFMPEG_SRC}/libavcodec/h2645_parse.c
    ${FFMPEG_SRC}/libavcodec/h264chroma.c
    ${FFMPEG_SRC}/libavcodec/h264qpel.c
    ${FFMPEG_SRC}/libavcodec/hpeldsp.c
    ${FFMPEG_SRC}/libavcodec/idctdsp.c
    ${FFMPEG_SRC}/libavcodec/imgconvert.c
    ${FFMPEG_SRC}/libavcodec/intrax8.c
    ${FFMPEG_SRC}/libavcodec/intrax8dsp.c
    ${FFMPEG_SRC}/libavcodec/ituh263dec.c
    ${FFMPEG_SRC}/libavcodec/jfdctfst.c
    ${FFMPEG_SRC}/libavcodec/jfdctint.c
    ${FFMPEG_SRC}/libavcodec/jni.c
    ${FFMPEG_SRC}/libavcodec/jrevdct.c
    ${FFMPEG_SRC}/libavcodec/lcevctab.c
    ${FFMPEG_SRC}/libavcodec/lossless_audiodsp.c
    ${FFMPEG_SRC}/libavcodec/lsp.c
    ${FFMPEG_SRC}/libavcodec/mathtables.c
    ${FFMPEG_SRC}/libavcodec/me_cmp.c
    ${FFMPEG_SRC}/libavcodec/mediacodec.c
    ${FFMPEG_SRC}/libavcodec/mpeg12framerate.c
    ${FFMPEG_SRC}/libavcodec/mpeg4video.c
    ${FFMPEG_SRC}/libavcodec/mpeg4videodec.c
    ${FFMPEG_SRC}/libavcodec/mpeg_er.c
    ${FFMPEG_SRC}/libavcodec/mpegpicture.c
    ${FFMPEG_SRC}/libavcodec/mpegutils.c
    ${FFMPEG_SRC}/libavcodec/mpegvideo.c
    ${FFMPEG_SRC}/libavcodec/mpegvideo_dec.c
    ${FFMPEG_SRC}/libavcodec/mpegvideo_motion.c
    ${FFMPEG_SRC}/libavcodec/mpegvideo_unquantize.c
    ${FFMPEG_SRC}/libavcodec/mpegvideodata.c
    ${FFMPEG_SRC}/libavcodec/msmpeg4.c
    ${FFMPEG_SRC}/libavcodec/msmpeg4_vc1_data.c
    ${FFMPEG_SRC}/libavcodec/msmpeg4data.c
    ${FFMPEG_SRC}/libavcodec/msmpeg4dec.c
    ${FFMPEG_SRC}/libavcodec/neon/mpegvideo.c
    ${FFMPEG_SRC}/libavcodec/options.c
    ${FFMPEG_SRC}/libavcodec/packet.c
    ${FFMPEG_SRC}/libavcodec/parser.c
    ${FFMPEG_SRC}/libavcodec/parsers.c
    ${FFMPEG_SRC}/libavcodec/profiles.c
    ${FFMPEG_SRC}/libavcodec/pthread.c
    ${FFMPEG_SRC}/libavcodec/pthread_frame.c
    ${FFMPEG_SRC}/libavcodec/pthread_slice.c
    ${FFMPEG_SRC}/libavcodec/qpeldsp.c
    ${FFMPEG_SRC}/libavcodec/qsv_api.c
    ${FFMPEG_SRC}/libavcodec/raw.c
    ${FFMPEG_SRC}/libavcodec/rl.c
    ${FFMPEG_SRC}/libavcodec/simple_idct.c
    ${FFMPEG_SRC}/libavcodec/sinewin.c
    ${FFMPEG_SRC}/libavcodec/startcode.c
    ${FFMPEG_SRC}/libavcodec/threadprogress.c
    ${FFMPEG_SRC}/libavcodec/tiff_common.c
    ${FFMPEG_SRC}/libavcodec/to_upper4.c
    ${FFMPEG_SRC}/libavcodec/utils.c
    ${FFMPEG_SRC}/libavcodec/vc1.c
    ${FFMPEG_SRC}/libavcodec/vc1_block.c
    ${FFMPEG_SRC}/libavcodec/vc1_loopfilter.c
    ${FFMPEG_SRC}/libavcodec/vc1_mc.c
    ${FFMPEG_SRC}/libavcodec/vc1_parser.c
    ${FFMPEG_SRC}/libavcodec/vc1_pred.c
    ${FFMPEG_SRC}/libavcodec/vc1data.c
    ${FFMPEG_SRC}/libavcodec/vc1dec.c
    ${FFMPEG_SRC}/libavcodec/vc1dsp.c
    ${FFMPEG_SRC}/libavcodec/version.c
    ${FFMPEG_SRC}/libavcodec/videodsp.c
    ${FFMPEG_SRC}/libavcodec/vlc.c
    ${FFMPEG_SRC}/libavcodec/vorbis_parser.c
    ${FFMPEG_SRC}/libavcodec/wma.c
    ${FFMPEG_SRC}/libavcodec/wma_common.c
    ${FFMPEG_SRC}/libavcodec/wma_freqs.c
    ${FFMPEG_SRC}/libavcodec/wmadec.c
    ${FFMPEG_SRC}/libavcodec/wmalosslessdec.c
    ${FFMPEG_SRC}/libavcodec/wmaprodec.c
    ${FFMPEG_SRC}/libavcodec/wmavoice.c
    ${FFMPEG_SRC}/libavcodec/wmv2data.c
    ${FFMPEG_SRC}/libavcodec/wmv2dec.c
    ${FFMPEG_SRC}/libavcodec/wmv2dsp.c
    ${FFMPEG_SRC}/libavcodec/xiph.c
    ${FFMPEG_SRC}/libavformat/allformats.c
    ${FFMPEG_SRC}/libavformat/asf.c
    ${FFMPEG_SRC}/libavformat/asf_tags.c
    ${FFMPEG_SRC}/libavformat/asfcrypt.c
    ${FFMPEG_SRC}/libavformat/asfdec_f.c
    ${FFMPEG_SRC}/libavformat/av1.c
    ${FFMPEG_SRC}/libavformat/avformat.c
    ${FFMPEG_SRC}/libavformat/avio.c
    ${FFMPEG_SRC}/libavformat/aviobuf.c
    ${FFMPEG_SRC}/libavformat/avlanguage.c
    ${FFMPEG_SRC}/libavformat/codecstring.c
    ${FFMPEG_SRC}/libavformat/demux.c
    ${FFMPEG_SRC}/libavformat/demux_utils.c
    ${FFMPEG_SRC}/libavformat/dump.c
    ${FFMPEG_SRC}/libavformat/dv.c
    ${FFMPEG_SRC}/libavformat/format.c
    ${FFMPEG_SRC}/libavformat/id3v1.c
    ${FFMPEG_SRC}/libavformat/id3v2.c
    ${FFMPEG_SRC}/libavformat/isom_tags.c
    ${FFMPEG_SRC}/libavformat/lcevc.c
    ${FFMPEG_SRC}/libavformat/metadata.c
    ${FFMPEG_SRC}/libavformat/mux.c
    ${FFMPEG_SRC}/libavformat/mux_utils.c
    ${FFMPEG_SRC}/libavformat/nal.c
    ${FFMPEG_SRC}/libavformat/options.c
    ${FFMPEG_SRC}/libavformat/os_support.c
    ${FFMPEG_SRC}/libavformat/packet_list.c
    ${FFMPEG_SRC}/libavformat/protocols.c
    ${FFMPEG_SRC}/libavformat/riff.c
    ${FFMPEG_SRC}/libavformat/riffdec.c
    ${FFMPEG_SRC}/libavformat/sdp.c
    ${FFMPEG_SRC}/libavformat/seek.c
    ${FFMPEG_SRC}/libavformat/url.c
    ${FFMPEG_SRC}/libavformat/urldecode.c
    ${FFMPEG_SRC}/libavformat/utils.c
    ${FFMPEG_SRC}/libavformat/version.c
    ${FFMPEG_SRC}/libavformat/vpcc.c
    ${FFMPEG_SRC}/libavutil/aarch64/cpu.c
    ${FFMPEG_SRC}/libavutil/aarch64/cpu_sme.S
    ${FFMPEG_SRC}/libavutil/aarch64/cpu_sve.S
    ${FFMPEG_SRC}/libavutil/aarch64/crc.S
    ${FFMPEG_SRC}/libavutil/aarch64/float_dsp_init.c
    ${FFMPEG_SRC}/libavutil/aarch64/float_dsp_neon.S
    ${FFMPEG_SRC}/libavutil/aarch64/tx_float_init.c
    ${FFMPEG_SRC}/libavutil/aarch64/tx_float_neon.S
    ${FFMPEG_SRC}/libavutil/adler32.c
    ${FFMPEG_SRC}/libavutil/aes.c
    ${FFMPEG_SRC}/libavutil/aes_ctr.c
    ${FFMPEG_SRC}/libavutil/ambient_viewing_environment.c
    ${FFMPEG_SRC}/libavutil/audio_fifo.c
    ${FFMPEG_SRC}/libavutil/avsscanf.c
    ${FFMPEG_SRC}/libavutil/avstring.c
    ${FFMPEG_SRC}/libavutil/base64.c
    ${FFMPEG_SRC}/libavutil/blowfish.c
    ${FFMPEG_SRC}/libavutil/bprint.c
    ${FFMPEG_SRC}/libavutil/buffer.c
    ${FFMPEG_SRC}/libavutil/camellia.c
    ${FFMPEG_SRC}/libavutil/cast5.c
    ${FFMPEG_SRC}/libavutil/channel_layout.c
    ${FFMPEG_SRC}/libavutil/container_fifo.c
    ${FFMPEG_SRC}/libavutil/cpu.c
    ${FFMPEG_SRC}/libavutil/crc.c
    ${FFMPEG_SRC}/libavutil/csp.c
    ${FFMPEG_SRC}/libavutil/des.c
    ${FFMPEG_SRC}/libavutil/detection_bbox.c
    ${FFMPEG_SRC}/libavutil/dict.c
    ${FFMPEG_SRC}/libavutil/display.c
    ${FFMPEG_SRC}/libavutil/dovi_meta.c
    ${FFMPEG_SRC}/libavutil/downmix_info.c
    ${FFMPEG_SRC}/libavutil/encryption_info.c
    ${FFMPEG_SRC}/libavutil/error.c
    ${FFMPEG_SRC}/libavutil/eval.c
    ${FFMPEG_SRC}/libavutil/executor.c
    ${FFMPEG_SRC}/libavutil/fifo.c
    ${FFMPEG_SRC}/libavutil/file.c
    ${FFMPEG_SRC}/libavutil/file_open.c
    ${FFMPEG_SRC}/libavutil/film_grain_params.c
    ${FFMPEG_SRC}/libavutil/fixed_dsp.c
    ${FFMPEG_SRC}/libavutil/float_dsp.c
    ${FFMPEG_SRC}/libavutil/float_scalarproduct.c
    ${FFMPEG_SRC}/libavutil/frame.c
    ${FFMPEG_SRC}/libavutil/hash.c
    ${FFMPEG_SRC}/libavutil/hdr_dynamic_metadata.c
    ${FFMPEG_SRC}/libavutil/hdr_dynamic_vivid_metadata.c
    ${FFMPEG_SRC}/libavutil/hmac.c
    ${FFMPEG_SRC}/libavutil/hwcontext.c
    ${FFMPEG_SRC}/libavutil/hwcontext_stub.c
    ${FFMPEG_SRC}/libavutil/iamf.c
    ${FFMPEG_SRC}/libavutil/imgutils.c
    ${FFMPEG_SRC}/libavutil/integer.c
    ${FFMPEG_SRC}/libavutil/intmath.c
    ${FFMPEG_SRC}/libavutil/lfg.c
    ${FFMPEG_SRC}/libavutil/lls.c
    ${FFMPEG_SRC}/libavutil/log.c
    ${FFMPEG_SRC}/libavutil/log2_tab.c
    ${FFMPEG_SRC}/libavutil/lzo.c
    ${FFMPEG_SRC}/libavutil/mastering_display_metadata.c
    ${FFMPEG_SRC}/libavutil/mathematics.c
    ${FFMPEG_SRC}/libavutil/md5.c
    ${FFMPEG_SRC}/libavutil/mem.c
    ${FFMPEG_SRC}/libavutil/murmur3.c
    ${FFMPEG_SRC}/libavutil/opt.c
    ${FFMPEG_SRC}/libavutil/parseutils.c
    ${FFMPEG_SRC}/libavutil/pixdesc.c
    ${FFMPEG_SRC}/libavutil/pixelutils.c
    ${FFMPEG_SRC}/libavutil/random_seed.c
    ${FFMPEG_SRC}/libavutil/rational.c
    ${FFMPEG_SRC}/libavutil/raw_color_params.c
    ${FFMPEG_SRC}/libavutil/rc4.c
    ${FFMPEG_SRC}/libavutil/refstruct.c
    ${FFMPEG_SRC}/libavutil/reverse.c
    ${FFMPEG_SRC}/libavutil/ripemd.c
    ${FFMPEG_SRC}/libavutil/samplefmt.c
    ${FFMPEG_SRC}/libavutil/sha.c
    ${FFMPEG_SRC}/libavutil/sha512.c
    ${FFMPEG_SRC}/libavutil/side_data.c
    ${FFMPEG_SRC}/libavutil/slicethread.c
    ${FFMPEG_SRC}/libavutil/spherical.c
    ${FFMPEG_SRC}/libavutil/stereo3d.c
    ${FFMPEG_SRC}/libavutil/tdrdi.c
    ${FFMPEG_SRC}/libavutil/tea.c
    ${FFMPEG_SRC}/libavutil/threadmessage.c
    ${FFMPEG_SRC}/libavutil/time.c
    ${FFMPEG_SRC}/libavutil/timecode.c
    ${FFMPEG_SRC}/libavutil/timecode_internal.c
    ${FFMPEG_SRC}/libavutil/timestamp.c
    ${FFMPEG_SRC}/libavutil/tree.c
    ${FFMPEG_SRC}/libavutil/twofish.c
    ${FFMPEG_SRC}/libavutil/tx.c
    ${FFMPEG_SRC}/libavutil/tx_double.c
    ${FFMPEG_SRC}/libavutil/tx_float.c
    ${FFMPEG_SRC}/libavutil/tx_int32.c
    ${FFMPEG_SRC}/libavutil/utils.c
    ${FFMPEG_SRC}/libavutil/uuid.c
    ${FFMPEG_SRC}/libavutil/version.c
    ${FFMPEG_SRC}/libavutil/video_enc_params.c
    ${FFMPEG_SRC}/libavutil/video_hint.c
    ${FFMPEG_SRC}/libavutil/xga_font_data.c
    ${FFMPEG_SRC}/libavutil/xtea.c
)
set(FFMPEG_SOURCES_armeabi-v7a
    ${FFMPEG_SRC}/compat/strtod.c
    ${FFMPEG_SRC}/libavcodec/aactab.c
    ${FFMPEG_SRC}/libavcodec/ac3_parser.c
    ${FFMPEG_SRC}/libavcodec/acelp_filters.c
    ${FFMPEG_SRC}/libavcodec/acelp_vectors.c
    ${FFMPEG_SRC}/libavcodec/adts_parser.c
    ${FFMPEG_SRC}/libavcodec/allcodecs.c
    ${FFMPEG_SRC}/libavcodec/arm/blockdsp_init_arm.c
    ${FFMPEG_SRC}/libavcodec/arm/blockdsp_init_neon.c
    ${FFMPEG_SRC}/libavcodec/arm/blockdsp_neon.S
    ${FFMPEG_SRC}/libavcodec/arm/h264chroma_init_arm.c
    ${FFMPEG_SRC}/libavcodec/arm/h264cmc_neon.S
    ${FFMPEG_SRC}/libavcodec/arm/h264qpel_init_arm.c
    ${FFMPEG_SRC}/libavcodec/arm/h264qpel_neon.S
    ${FFMPEG_SRC}/libavcodec/arm/hpeldsp_arm.S
    ${FFMPEG_SRC}/libavcodec/arm/hpeldsp_armv6.S
    ${FFMPEG_SRC}/libavcodec/arm/hpeldsp_init_arm.c
    ${FFMPEG_SRC}/libavcodec/arm/hpeldsp_init_armv6.c
    ${FFMPEG_SRC}/libavcodec/arm/hpeldsp_init_neon.c
    ${FFMPEG_SRC}/libavcodec/arm/hpeldsp_neon.S
    ${FFMPEG_SRC}/libavcodec/arm/idctdsp_arm.S
    ${FFMPEG_SRC}/libavcodec/arm/idctdsp_armv6.S
    ${FFMPEG_SRC}/libavcodec/arm/idctdsp_init_arm.c
    ${FFMPEG_SRC}/libavcodec/arm/idctdsp_init_armv5te.c
    ${FFMPEG_SRC}/libavcodec/arm/idctdsp_init_armv6.c
    ${FFMPEG_SRC}/libavcodec/arm/idctdsp_init_neon.c
    ${FFMPEG_SRC}/libavcodec/arm/idctdsp_neon.S
    ${FFMPEG_SRC}/libavcodec/arm/jrevdct_arm.S
    ${FFMPEG_SRC}/libavcodec/arm/lossless_audiodsp_init_arm.c
    ${FFMPEG_SRC}/libavcodec/arm/lossless_audiodsp_neon.S
    ${FFMPEG_SRC}/libavcodec/arm/me_cmp_armv6.S
    ${FFMPEG_SRC}/libavcodec/arm/me_cmp_init_arm.c
    ${FFMPEG_SRC}/libavcodec/arm/mpegvideo_arm.c
    ${FFMPEG_SRC}/libavcodec/arm/mpegvideo_armv5te.c
    ${FFMPEG_SRC}/libavcodec/arm/mpegvideo_armv5te_s.S
    ${FFMPEG_SRC}/libavcodec/arm/mpegvideo_neon.S
    ${FFMPEG_SRC}/libavcodec/arm/simple_idct_arm.S
    ${FFMPEG_SRC}/libavcodec/arm/simple_idct_armv5te.S
    ${FFMPEG_SRC}/libavcodec/arm/simple_idct_armv6.S
    ${FFMPEG_SRC}/libavcodec/arm/simple_idct_neon.S
    ${FFMPEG_SRC}/libavcodec/arm/startcode_armv6.S
    ${FFMPEG_SRC}/libavcodec/arm/vc1dsp_init_arm.c
    ${FFMPEG_SRC}/libavcodec/arm/vc1dsp_init_neon.c
    ${FFMPEG_SRC}/libavcodec/arm/vc1dsp_neon.S
    ${FFMPEG_SRC}/libavcodec/arm/videodsp_armv5te.S
    ${FFMPEG_SRC}/libavcodec/arm/videodsp_init_arm.c
    ${FFMPEG_SRC}/libavcodec/arm/videodsp_init_armv5te.c
    ${FFMPEG_SRC}/libavcodec/avcodec.c
    ${FFMPEG_SRC}/libavcodec/avdct.c
    ${FFMPEG_SRC}/libavcodec/bitstream.c
    ${FFMPEG_SRC}/libavcodec/bitstream_filters.c
    ${FFMPEG_SRC}/libavcodec/blockdsp.c
    ${FFMPEG_SRC}/libavcodec/bsf.c
    ${FFMPEG_SRC}/libavcodec/celp_filters.c
    ${FFMPEG_SRC}/libavcodec/codec_desc.c
    ${FFMPEG_SRC}/libavcodec/codec_par.c
    ${FFMPEG_SRC}/libavcodec/d3d11va.c
    ${FFMPEG_SRC}/libavcodec/decode.c
    ${FFMPEG_SRC}/libavcodec/dirac.c
    ${FFMPEG_SRC}/libavcodec/dv_profile.c
    ${FFMPEG_SRC}/libavcodec/encode.c
    ${FFMPEG_SRC}/libavcodec/error_resilience.c
    ${FFMPEG_SRC}/libavcodec/exif.c
    ${FFMPEG_SRC}/libavcodec/faandct.c
    ${FFMPEG_SRC}/libavcodec/faanidct.c
    ${FFMPEG_SRC}/libavcodec/fdctdsp.c
    ${FFMPEG_SRC}/libavcodec/get_buffer.c
    ${FFMPEG_SRC}/libavcodec/h263.c
    ${FFMPEG_SRC}/libavcodec/h263data.c
    ${FFMPEG_SRC}/libavcodec/h263dec.c
    ${FFMPEG_SRC}/libavcodec/h263dsp.c
    ${FFMPEG_SRC}/libavcodec/h2645_parse.c
    ${FFMPEG_SRC}/libavcodec/h264chroma.c
    ${FFMPEG_SRC}/libavcodec/h264qpel.c
    ${FFMPEG_SRC}/libavcodec/hpeldsp.c
    ${FFMPEG_SRC}/libavcodec/idctdsp.c
    ${FFMPEG_SRC}/libavcodec/imgconvert.c
    ${FFMPEG_SRC}/libavcodec/intrax8.c
    ${FFMPEG_SRC}/libavcodec/intrax8dsp.c
    ${FFMPEG_SRC}/libavcodec/ituh263dec.c
    ${FFMPEG_SRC}/libavcodec/jfdctfst.c
    ${FFMPEG_SRC}/libavcodec/jfdctint.c
    ${FFMPEG_SRC}/libavcodec/jni.c
    ${FFMPEG_SRC}/libavcodec/jrevdct.c
    ${FFMPEG_SRC}/libavcodec/lcevctab.c
    ${FFMPEG_SRC}/libavcodec/lossless_audiodsp.c
    ${FFMPEG_SRC}/libavcodec/lsp.c
    ${FFMPEG_SRC}/libavcodec/mathtables.c
    ${FFMPEG_SRC}/libavcodec/me_cmp.c
    ${FFMPEG_SRC}/libavcodec/mediacodec.c
    ${FFMPEG_SRC}/libavcodec/mpeg12framerate.c
    ${FFMPEG_SRC}/libavcodec/mpeg4video.c
    ${FFMPEG_SRC}/libavcodec/mpeg4videodec.c
    ${FFMPEG_SRC}/libavcodec/mpeg_er.c
    ${FFMPEG_SRC}/libavcodec/mpegpicture.c
    ${FFMPEG_SRC}/libavcodec/mpegutils.c
    ${FFMPEG_SRC}/libavcodec/mpegvideo.c
    ${FFMPEG_SRC}/libavcodec/mpegvideo_dec.c
    ${FFMPEG_SRC}/libavcodec/mpegvideo_motion.c
    ${FFMPEG_SRC}/libavcodec/mpegvideo_unquantize.c
    ${FFMPEG_SRC}/libavcodec/mpegvideodata.c
    ${FFMPEG_SRC}/libavcodec/msmpeg4.c
    ${FFMPEG_SRC}/libavcodec/msmpeg4_vc1_data.c
    ${FFMPEG_SRC}/libavcodec/msmpeg4data.c
    ${FFMPEG_SRC}/libavcodec/msmpeg4dec.c
    ${FFMPEG_SRC}/libavcodec/neon/mpegvideo.c
    ${FFMPEG_SRC}/libavcodec/options.c
    ${FFMPEG_SRC}/libavcodec/packet.c
    ${FFMPEG_SRC}/libavcodec/parser.c
    ${FFMPEG_SRC}/libavcodec/parsers.c
    ${FFMPEG_SRC}/libavcodec/profiles.c
    ${FFMPEG_SRC}/libavcodec/pthread.c
    ${FFMPEG_SRC}/libavcodec/pthread_frame.c
    ${FFMPEG_SRC}/libavcodec/pthread_slice.c
    ${FFMPEG_SRC}/libavcodec/qpeldsp.c
    ${FFMPEG_SRC}/libavcodec/qsv_api.c
    ${FFMPEG_SRC}/libavcodec/raw.c
    ${FFMPEG_SRC}/libavcodec/rl.c
    ${FFMPEG_SRC}/libavcodec/simple_idct.c
    ${FFMPEG_SRC}/libavcodec/sinewin.c
    ${FFMPEG_SRC}/libavcodec/startcode.c
    ${FFMPEG_SRC}/libavcodec/threadprogress.c
    ${FFMPEG_SRC}/libavcodec/tiff_common.c
    ${FFMPEG_SRC}/libavcodec/to_upper4.c
    ${FFMPEG_SRC}/libavcodec/utils.c
    ${FFMPEG_SRC}/libavcodec/vc1.c
    ${FFMPEG_SRC}/libavcodec/vc1_block.c
    ${FFMPEG_SRC}/libavcodec/vc1_loopfilter.c
    ${FFMPEG_SRC}/libavcodec/vc1_mc.c
    ${FFMPEG_SRC}/libavcodec/vc1_parser.c
    ${FFMPEG_SRC}/libavcodec/vc1_pred.c
    ${FFMPEG_SRC}/libavcodec/vc1data.c
    ${FFMPEG_SRC}/libavcodec/vc1dec.c
    ${FFMPEG_SRC}/libavcodec/vc1dsp.c
    ${FFMPEG_SRC}/libavcodec/version.c
    ${FFMPEG_SRC}/libavcodec/videodsp.c
    ${FFMPEG_SRC}/libavcodec/vlc.c
    ${FFMPEG_SRC}/libavcodec/vorbis_parser.c
    ${FFMPEG_SRC}/libavcodec/wma.c
    ${FFMPEG_SRC}/libavcodec/wma_common.c
    ${FFMPEG_SRC}/libavcodec/wma_freqs.c
    ${FFMPEG_SRC}/libavcodec/wmadec.c
    ${FFMPEG_SRC}/libavcodec/wmalosslessdec.c
    ${FFMPEG_SRC}/libavcodec/wmaprodec.c
    ${FFMPEG_SRC}/libavcodec/wmavoice.c
    ${FFMPEG_SRC}/libavcodec/wmv2data.c
    ${FFMPEG_SRC}/libavcodec/wmv2dec.c
    ${FFMPEG_SRC}/libavcodec/wmv2dsp.c
    ${FFMPEG_SRC}/libavcodec/xiph.c
    ${FFMPEG_SRC}/libavformat/allformats.c
    ${FFMPEG_SRC}/libavformat/asf.c
    ${FFMPEG_SRC}/libavformat/asf_tags.c
    ${FFMPEG_SRC}/libavformat/asfcrypt.c
    ${FFMPEG_SRC}/libavformat/asfdec_f.c
    ${FFMPEG_SRC}/libavformat/av1.c
    ${FFMPEG_SRC}/libavformat/avformat.c
    ${FFMPEG_SRC}/libavformat/avio.c
    ${FFMPEG_SRC}/libavformat/aviobuf.c
    ${FFMPEG_SRC}/libavformat/avlanguage.c
    ${FFMPEG_SRC}/libavformat/codecstring.c
    ${FFMPEG_SRC}/libavformat/demux.c
    ${FFMPEG_SRC}/libavformat/demux_utils.c
    ${FFMPEG_SRC}/libavformat/dump.c
    ${FFMPEG_SRC}/libavformat/dv.c
    ${FFMPEG_SRC}/libavformat/format.c
    ${FFMPEG_SRC}/libavformat/id3v1.c
    ${FFMPEG_SRC}/libavformat/id3v2.c
    ${FFMPEG_SRC}/libavformat/isom_tags.c
    ${FFMPEG_SRC}/libavformat/lcevc.c
    ${FFMPEG_SRC}/libavformat/metadata.c
    ${FFMPEG_SRC}/libavformat/mux.c
    ${FFMPEG_SRC}/libavformat/mux_utils.c
    ${FFMPEG_SRC}/libavformat/nal.c
    ${FFMPEG_SRC}/libavformat/options.c
    ${FFMPEG_SRC}/libavformat/os_support.c
    ${FFMPEG_SRC}/libavformat/packet_list.c
    ${FFMPEG_SRC}/libavformat/protocols.c
    ${FFMPEG_SRC}/libavformat/riff.c
    ${FFMPEG_SRC}/libavformat/riffdec.c
    ${FFMPEG_SRC}/libavformat/sdp.c
    ${FFMPEG_SRC}/libavformat/seek.c
    ${FFMPEG_SRC}/libavformat/url.c
    ${FFMPEG_SRC}/libavformat/urldecode.c
    ${FFMPEG_SRC}/libavformat/utils.c
    ${FFMPEG_SRC}/libavformat/version.c
    ${FFMPEG_SRC}/libavformat/vpcc.c
    ${FFMPEG_SRC}/libavutil/adler32.c
    ${FFMPEG_SRC}/libavutil/aes.c
    ${FFMPEG_SRC}/libavutil/aes_ctr.c
    ${FFMPEG_SRC}/libavutil/ambient_viewing_environment.c
    ${FFMPEG_SRC}/libavutil/arm/cpu.c
    ${FFMPEG_SRC}/libavutil/arm/float_dsp_init_arm.c
    ${FFMPEG_SRC}/libavutil/arm/float_dsp_init_neon.c
    ${FFMPEG_SRC}/libavutil/arm/float_dsp_init_vfp.c
    ${FFMPEG_SRC}/libavutil/arm/float_dsp_neon.S
    ${FFMPEG_SRC}/libavutil/arm/float_dsp_vfp.S
    ${FFMPEG_SRC}/libavutil/audio_fifo.c
    ${FFMPEG_SRC}/libavutil/avsscanf.c
    ${FFMPEG_SRC}/libavutil/avstring.c
    ${FFMPEG_SRC}/libavutil/base64.c
    ${FFMPEG_SRC}/libavutil/blowfish.c
    ${FFMPEG_SRC}/libavutil/bprint.c
    ${FFMPEG_SRC}/libavutil/buffer.c
    ${FFMPEG_SRC}/libavutil/camellia.c
    ${FFMPEG_SRC}/libavutil/cast5.c
    ${FFMPEG_SRC}/libavutil/channel_layout.c
    ${FFMPEG_SRC}/libavutil/container_fifo.c
    ${FFMPEG_SRC}/libavutil/cpu.c
    ${FFMPEG_SRC}/libavutil/crc.c
    ${FFMPEG_SRC}/libavutil/csp.c
    ${FFMPEG_SRC}/libavutil/des.c
    ${FFMPEG_SRC}/libavutil/detection_bbox.c
    ${FFMPEG_SRC}/libavutil/dict.c
    ${FFMPEG_SRC}/libavutil/display.c
    ${FFMPEG_SRC}/libavutil/dovi_meta.c
    ${FFMPEG_SRC}/libavutil/downmix_info.c
    ${FFMPEG_SRC}/libavutil/encryption_info.c
    ${FFMPEG_SRC}/libavutil/error.c
    ${FFMPEG_SRC}/libavutil/eval.c
    ${FFMPEG_SRC}/libavutil/executor.c
    ${FFMPEG_SRC}/libavutil/fifo.c
    ${FFMPEG_SRC}/libavutil/file.c
    ${FFMPEG_SRC}/libavutil/file_open.c
    ${FFMPEG_SRC}/libavutil/film_grain_params.c
    ${FFMPEG_SRC}/libavutil/fixed_dsp.c
    ${FFMPEG_SRC}/libavutil/float_dsp.c
    ${FFMPEG_SRC}/libavutil/float_scalarproduct.c
    ${FFMPEG_SRC}/libavutil/frame.c
    ${FFMPEG_SRC}/libavutil/hash.c
    ${FFMPEG_SRC}/libavutil/hdr_dynamic_metadata.c
    ${FFMPEG_SRC}/libavutil/hdr_dynamic_vivid_metadata.c
    ${FFMPEG_SRC}/libavutil/hmac.c
    ${FFMPEG_SRC}/libavutil/hwcontext.c
    ${FFMPEG_SRC}/libavutil/hwcontext_stub.c
    ${FFMPEG_SRC}/libavutil/iamf.c
    ${FFMPEG_SRC}/libavutil/imgutils.c
    ${FFMPEG_SRC}/libavutil/integer.c
    ${FFMPEG_SRC}/libavutil/intmath.c
    ${FFMPEG_SRC}/libavutil/lfg.c
    ${FFMPEG_SRC}/libavutil/lls.c
    ${FFMPEG_SRC}/libavutil/log.c
    ${FFMPEG_SRC}/libavutil/log2_tab.c
    ${FFMPEG_SRC}/libavutil/lzo.c
    ${FFMPEG_SRC}/libavutil/mastering_display_metadata.c
    ${FFMPEG_SRC}/libavutil/mathematics.c
    ${FFMPEG_SRC}/libavutil/md5.c
    ${FFMPEG_SRC}/libavutil/mem.c
    ${FFMPEG_SRC}/libavutil/murmur3.c
    ${FFMPEG_SRC}/libavutil/opt.c
    ${FFMPEG_SRC}/libavutil/parseutils.c
    ${FFMPEG_SRC}/libavutil/pixdesc.c
    ${FFMPEG_SRC}/libavutil/pixelutils.c
    ${FFMPEG_SRC}/libavutil/random_seed.c
    ${FFMPEG_SRC}/libavutil/rational.c
    ${FFMPEG_SRC}/libavutil/raw_color_params.c
    ${FFMPEG_SRC}/libavutil/rc4.c
    ${FFMPEG_SRC}/libavutil/refstruct.c
    ${FFMPEG_SRC}/libavutil/reverse.c
    ${FFMPEG_SRC}/libavutil/ripemd.c
    ${FFMPEG_SRC}/libavutil/samplefmt.c
    ${FFMPEG_SRC}/libavutil/sha.c
    ${FFMPEG_SRC}/libavutil/sha512.c
    ${FFMPEG_SRC}/libavutil/side_data.c
    ${FFMPEG_SRC}/libavutil/slicethread.c
    ${FFMPEG_SRC}/libavutil/spherical.c
    ${FFMPEG_SRC}/libavutil/stereo3d.c
    ${FFMPEG_SRC}/libavutil/tdrdi.c
    ${FFMPEG_SRC}/libavutil/tea.c
    ${FFMPEG_SRC}/libavutil/threadmessage.c
    ${FFMPEG_SRC}/libavutil/time.c
    ${FFMPEG_SRC}/libavutil/timecode.c
    ${FFMPEG_SRC}/libavutil/timecode_internal.c
    ${FFMPEG_SRC}/libavutil/timestamp.c
    ${FFMPEG_SRC}/libavutil/tree.c
    ${FFMPEG_SRC}/libavutil/twofish.c
    ${FFMPEG_SRC}/libavutil/tx.c
    ${FFMPEG_SRC}/libavutil/tx_double.c
    ${FFMPEG_SRC}/libavutil/tx_float.c
    ${FFMPEG_SRC}/libavutil/tx_int32.c
    ${FFMPEG_SRC}/libavutil/utils.c
    ${FFMPEG_SRC}/libavutil/uuid.c
    ${FFMPEG_SRC}/libavutil/version.c
    ${FFMPEG_SRC}/libavutil/video_enc_params.c
    ${FFMPEG_SRC}/libavutil/video_hint.c
    ${FFMPEG_SRC}/libavutil/xga_font_data.c
    ${FFMPEG_SRC}/libavutil/xtea.c
)
set(FFMPEG_SOURCES_x86_64
    ${FFMPEG_SRC}/compat/strtod.c
    ${FFMPEG_SRC}/libavcodec/aactab.c
    ${FFMPEG_SRC}/libavcodec/ac3_parser.c
    ${FFMPEG_SRC}/libavcodec/acelp_filters.c
    ${FFMPEG_SRC}/libavcodec/acelp_vectors.c
    ${FFMPEG_SRC}/libavcodec/adts_parser.c
    ${FFMPEG_SRC}/libavcodec/allcodecs.c
    ${FFMPEG_SRC}/libavcodec/avcodec.c
    ${FFMPEG_SRC}/libavcodec/avdct.c
    ${FFMPEG_SRC}/libavcodec/bitstream.c
    ${FFMPEG_SRC}/libavcodec/bitstream_filters.c
    ${FFMPEG_SRC}/libavcodec/blockdsp.c
    ${FFMPEG_SRC}/libavcodec/bsf.c
    ${FFMPEG_SRC}/libavcodec/celp_filters.c
    ${FFMPEG_SRC}/libavcodec/codec_desc.c
    ${FFMPEG_SRC}/libavcodec/codec_par.c
    ${FFMPEG_SRC}/libavcodec/d3d11va.c
    ${FFMPEG_SRC}/libavcodec/decode.c
    ${FFMPEG_SRC}/libavcodec/dirac.c
    ${FFMPEG_SRC}/libavcodec/dv_profile.c
    ${FFMPEG_SRC}/libavcodec/encode.c
    ${FFMPEG_SRC}/libavcodec/error_resilience.c
    ${FFMPEG_SRC}/libavcodec/exif.c
    ${FFMPEG_SRC}/libavcodec/faandct.c
    ${FFMPEG_SRC}/libavcodec/faanidct.c
    ${FFMPEG_SRC}/libavcodec/fdctdsp.c
    ${FFMPEG_SRC}/libavcodec/get_buffer.c
    ${FFMPEG_SRC}/libavcodec/h263.c
    ${FFMPEG_SRC}/libavcodec/h263data.c
    ${FFMPEG_SRC}/libavcodec/h263dec.c
    ${FFMPEG_SRC}/libavcodec/h263dsp.c
    ${FFMPEG_SRC}/libavcodec/h2645_parse.c
    ${FFMPEG_SRC}/libavcodec/h264chroma.c
    ${FFMPEG_SRC}/libavcodec/h264qpel.c
    ${FFMPEG_SRC}/libavcodec/hpeldsp.c
    ${FFMPEG_SRC}/libavcodec/idctdsp.c
    ${FFMPEG_SRC}/libavcodec/imgconvert.c
    ${FFMPEG_SRC}/libavcodec/intrax8.c
    ${FFMPEG_SRC}/libavcodec/intrax8dsp.c
    ${FFMPEG_SRC}/libavcodec/ituh263dec.c
    ${FFMPEG_SRC}/libavcodec/jfdctfst.c
    ${FFMPEG_SRC}/libavcodec/jfdctint.c
    ${FFMPEG_SRC}/libavcodec/jni.c
    ${FFMPEG_SRC}/libavcodec/jrevdct.c
    ${FFMPEG_SRC}/libavcodec/lcevctab.c
    ${FFMPEG_SRC}/libavcodec/lossless_audiodsp.c
    ${FFMPEG_SRC}/libavcodec/lsp.c
    ${FFMPEG_SRC}/libavcodec/mathtables.c
    ${FFMPEG_SRC}/libavcodec/me_cmp.c
    ${FFMPEG_SRC}/libavcodec/mediacodec.c
    ${FFMPEG_SRC}/libavcodec/mpeg12framerate.c
    ${FFMPEG_SRC}/libavcodec/mpeg4video.c
    ${FFMPEG_SRC}/libavcodec/mpeg4videodec.c
    ${FFMPEG_SRC}/libavcodec/mpeg_er.c
    ${FFMPEG_SRC}/libavcodec/mpegpicture.c
    ${FFMPEG_SRC}/libavcodec/mpegutils.c
    ${FFMPEG_SRC}/libavcodec/mpegvideo.c
    ${FFMPEG_SRC}/libavcodec/mpegvideo_dec.c
    ${FFMPEG_SRC}/libavcodec/mpegvideo_motion.c
    ${FFMPEG_SRC}/libavcodec/mpegvideo_unquantize.c
    ${FFMPEG_SRC}/libavcodec/mpegvideodata.c
    ${FFMPEG_SRC}/libavcodec/msmpeg4.c
    ${FFMPEG_SRC}/libavcodec/msmpeg4_vc1_data.c
    ${FFMPEG_SRC}/libavcodec/msmpeg4data.c
    ${FFMPEG_SRC}/libavcodec/msmpeg4dec.c
    ${FFMPEG_SRC}/libavcodec/options.c
    ${FFMPEG_SRC}/libavcodec/packet.c
    ${FFMPEG_SRC}/libavcodec/parser.c
    ${FFMPEG_SRC}/libavcodec/parsers.c
    ${FFMPEG_SRC}/libavcodec/profiles.c
    ${FFMPEG_SRC}/libavcodec/pthread.c
    ${FFMPEG_SRC}/libavcodec/pthread_frame.c
    ${FFMPEG_SRC}/libavcodec/pthread_slice.c
    ${FFMPEG_SRC}/libavcodec/qpeldsp.c
    ${FFMPEG_SRC}/libavcodec/qsv_api.c
    ${FFMPEG_SRC}/libavcodec/raw.c
    ${FFMPEG_SRC}/libavcodec/rl.c
    ${FFMPEG_SRC}/libavcodec/simple_idct.c
    ${FFMPEG_SRC}/libavcodec/sinewin.c
    ${FFMPEG_SRC}/libavcodec/startcode.c
    ${FFMPEG_SRC}/libavcodec/threadprogress.c
    ${FFMPEG_SRC}/libavcodec/tiff_common.c
    ${FFMPEG_SRC}/libavcodec/to_upper4.c
    ${FFMPEG_SRC}/libavcodec/utils.c
    ${FFMPEG_SRC}/libavcodec/vc1.c
    ${FFMPEG_SRC}/libavcodec/vc1_block.c
    ${FFMPEG_SRC}/libavcodec/vc1_loopfilter.c
    ${FFMPEG_SRC}/libavcodec/vc1_mc.c
    ${FFMPEG_SRC}/libavcodec/vc1_parser.c
    ${FFMPEG_SRC}/libavcodec/vc1_pred.c
    ${FFMPEG_SRC}/libavcodec/vc1data.c
    ${FFMPEG_SRC}/libavcodec/vc1dec.c
    ${FFMPEG_SRC}/libavcodec/vc1dsp.c
    ${FFMPEG_SRC}/libavcodec/version.c
    ${FFMPEG_SRC}/libavcodec/videodsp.c
    ${FFMPEG_SRC}/libavcodec/vlc.c
    ${FFMPEG_SRC}/libavcodec/vorbis_parser.c
    ${FFMPEG_SRC}/libavcodec/wma.c
    ${FFMPEG_SRC}/libavcodec/wma_common.c
    ${FFMPEG_SRC}/libavcodec/wma_freqs.c
    ${FFMPEG_SRC}/libavcodec/wmadec.c
    ${FFMPEG_SRC}/libavcodec/wmalosslessdec.c
    ${FFMPEG_SRC}/libavcodec/wmaprodec.c
    ${FFMPEG_SRC}/libavcodec/wmavoice.c
    ${FFMPEG_SRC}/libavcodec/wmv2data.c
    ${FFMPEG_SRC}/libavcodec/wmv2dec.c
    ${FFMPEG_SRC}/libavcodec/wmv2dsp.c
    ${FFMPEG_SRC}/libavcodec/xiph.c
    ${FFMPEG_SRC}/libavformat/allformats.c
    ${FFMPEG_SRC}/libavformat/asf.c
    ${FFMPEG_SRC}/libavformat/asf_tags.c
    ${FFMPEG_SRC}/libavformat/asfcrypt.c
    ${FFMPEG_SRC}/libavformat/asfdec_f.c
    ${FFMPEG_SRC}/libavformat/av1.c
    ${FFMPEG_SRC}/libavformat/avformat.c
    ${FFMPEG_SRC}/libavformat/avio.c
    ${FFMPEG_SRC}/libavformat/aviobuf.c
    ${FFMPEG_SRC}/libavformat/avlanguage.c
    ${FFMPEG_SRC}/libavformat/codecstring.c
    ${FFMPEG_SRC}/libavformat/demux.c
    ${FFMPEG_SRC}/libavformat/demux_utils.c
    ${FFMPEG_SRC}/libavformat/dump.c
    ${FFMPEG_SRC}/libavformat/dv.c
    ${FFMPEG_SRC}/libavformat/format.c
    ${FFMPEG_SRC}/libavformat/id3v1.c
    ${FFMPEG_SRC}/libavformat/id3v2.c
    ${FFMPEG_SRC}/libavformat/isom_tags.c
    ${FFMPEG_SRC}/libavformat/lcevc.c
    ${FFMPEG_SRC}/libavformat/metadata.c
    ${FFMPEG_SRC}/libavformat/mux.c
    ${FFMPEG_SRC}/libavformat/mux_utils.c
    ${FFMPEG_SRC}/libavformat/nal.c
    ${FFMPEG_SRC}/libavformat/options.c
    ${FFMPEG_SRC}/libavformat/os_support.c
    ${FFMPEG_SRC}/libavformat/packet_list.c
    ${FFMPEG_SRC}/libavformat/protocols.c
    ${FFMPEG_SRC}/libavformat/riff.c
    ${FFMPEG_SRC}/libavformat/riffdec.c
    ${FFMPEG_SRC}/libavformat/sdp.c
    ${FFMPEG_SRC}/libavformat/seek.c
    ${FFMPEG_SRC}/libavformat/url.c
    ${FFMPEG_SRC}/libavformat/urldecode.c
    ${FFMPEG_SRC}/libavformat/utils.c
    ${FFMPEG_SRC}/libavformat/version.c
    ${FFMPEG_SRC}/libavformat/vpcc.c
    ${FFMPEG_SRC}/libavutil/adler32.c
    ${FFMPEG_SRC}/libavutil/aes.c
    ${FFMPEG_SRC}/libavutil/aes_ctr.c
    ${FFMPEG_SRC}/libavutil/ambient_viewing_environment.c
    ${FFMPEG_SRC}/libavutil/audio_fifo.c
    ${FFMPEG_SRC}/libavutil/avsscanf.c
    ${FFMPEG_SRC}/libavutil/avstring.c
    ${FFMPEG_SRC}/libavutil/base64.c
    ${FFMPEG_SRC}/libavutil/blowfish.c
    ${FFMPEG_SRC}/libavutil/bprint.c
    ${FFMPEG_SRC}/libavutil/buffer.c
    ${FFMPEG_SRC}/libavutil/camellia.c
    ${FFMPEG_SRC}/libavutil/cast5.c
    ${FFMPEG_SRC}/libavutil/channel_layout.c
    ${FFMPEG_SRC}/libavutil/container_fifo.c
    ${FFMPEG_SRC}/libavutil/cpu.c
    ${FFMPEG_SRC}/libavutil/crc.c
    ${FFMPEG_SRC}/libavutil/csp.c
    ${FFMPEG_SRC}/libavutil/des.c
    ${FFMPEG_SRC}/libavutil/detection_bbox.c
    ${FFMPEG_SRC}/libavutil/dict.c
    ${FFMPEG_SRC}/libavutil/display.c
    ${FFMPEG_SRC}/libavutil/dovi_meta.c
    ${FFMPEG_SRC}/libavutil/downmix_info.c
    ${FFMPEG_SRC}/libavutil/encryption_info.c
    ${FFMPEG_SRC}/libavutil/error.c
    ${FFMPEG_SRC}/libavutil/eval.c
    ${FFMPEG_SRC}/libavutil/executor.c
    ${FFMPEG_SRC}/libavutil/fifo.c
    ${FFMPEG_SRC}/libavutil/file.c
    ${FFMPEG_SRC}/libavutil/file_open.c
    ${FFMPEG_SRC}/libavutil/film_grain_params.c
    ${FFMPEG_SRC}/libavutil/fixed_dsp.c
    ${FFMPEG_SRC}/libavutil/float_dsp.c
    ${FFMPEG_SRC}/libavutil/float_scalarproduct.c
    ${FFMPEG_SRC}/libavutil/frame.c
    ${FFMPEG_SRC}/libavutil/hash.c
    ${FFMPEG_SRC}/libavutil/hdr_dynamic_metadata.c
    ${FFMPEG_SRC}/libavutil/hdr_dynamic_vivid_metadata.c
    ${FFMPEG_SRC}/libavutil/hmac.c
    ${FFMPEG_SRC}/libavutil/hwcontext.c
    ${FFMPEG_SRC}/libavutil/hwcontext_stub.c
    ${FFMPEG_SRC}/libavutil/iamf.c
    ${FFMPEG_SRC}/libavutil/imgutils.c
    ${FFMPEG_SRC}/libavutil/integer.c
    ${FFMPEG_SRC}/libavutil/intmath.c
    ${FFMPEG_SRC}/libavutil/lfg.c
    ${FFMPEG_SRC}/libavutil/lls.c
    ${FFMPEG_SRC}/libavutil/log.c
    ${FFMPEG_SRC}/libavutil/log2_tab.c
    ${FFMPEG_SRC}/libavutil/lzo.c
    ${FFMPEG_SRC}/libavutil/mastering_display_metadata.c
    ${FFMPEG_SRC}/libavutil/mathematics.c
    ${FFMPEG_SRC}/libavutil/md5.c
    ${FFMPEG_SRC}/libavutil/mem.c
    ${FFMPEG_SRC}/libavutil/murmur3.c
    ${FFMPEG_SRC}/libavutil/opt.c
    ${FFMPEG_SRC}/libavutil/parseutils.c
    ${FFMPEG_SRC}/libavutil/pixdesc.c
    ${FFMPEG_SRC}/libavutil/pixelutils.c
    ${FFMPEG_SRC}/libavutil/random_seed.c
    ${FFMPEG_SRC}/libavutil/rational.c
    ${FFMPEG_SRC}/libavutil/raw_color_params.c
    ${FFMPEG_SRC}/libavutil/rc4.c
    ${FFMPEG_SRC}/libavutil/refstruct.c
    ${FFMPEG_SRC}/libavutil/reverse.c
    ${FFMPEG_SRC}/libavutil/ripemd.c
    ${FFMPEG_SRC}/libavutil/samplefmt.c
    ${FFMPEG_SRC}/libavutil/sha.c
    ${FFMPEG_SRC}/libavutil/sha512.c
    ${FFMPEG_SRC}/libavutil/side_data.c
    ${FFMPEG_SRC}/libavutil/slicethread.c
    ${FFMPEG_SRC}/libavutil/spherical.c
    ${FFMPEG_SRC}/libavutil/stereo3d.c
    ${FFMPEG_SRC}/libavutil/tdrdi.c
    ${FFMPEG_SRC}/libavutil/tea.c
    ${FFMPEG_SRC}/libavutil/threadmessage.c
    ${FFMPEG_SRC}/libavutil/time.c
    ${FFMPEG_SRC}/libavutil/timecode.c
    ${FFMPEG_SRC}/libavutil/timecode_internal.c
    ${FFMPEG_SRC}/libavutil/timestamp.c
    ${FFMPEG_SRC}/libavutil/tree.c
    ${FFMPEG_SRC}/libavutil/twofish.c
    ${FFMPEG_SRC}/libavutil/tx.c
    ${FFMPEG_SRC}/libavutil/tx_double.c
    ${FFMPEG_SRC}/libavutil/tx_float.c
    ${FFMPEG_SRC}/libavutil/tx_int32.c
    ${FFMPEG_SRC}/libavutil/utils.c
    ${FFMPEG_SRC}/libavutil/uuid.c
    ${FFMPEG_SRC}/libavutil/version.c
    ${FFMPEG_SRC}/libavutil/video_enc_params.c
    ${FFMPEG_SRC}/libavutil/video_hint.c
    ${FFMPEG_SRC}/libavutil/xga_font_data.c
    ${FFMPEG_SRC}/libavutil/xtea.c
)
